
package pl.bb.broker.company.invoices.rest.bankclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBankService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBankService {


    /**
     * 
     * @param transfer
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IBankService/transferMoney")
    @WebResult(name = "transferMoneyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "transferMoney", targetNamespace = "http://tempuri.org/", className = "pl.bb.broker.company.invoices.rest.bankclient.TransferMoney")
    @ResponseWrapper(localName = "transferMoneyResponse", targetNamespace = "http://tempuri.org/", className = "pl.bb.broker.company.invoices.rest.bankclient.TransferMoneyResponse")
    public String transferMoney(
        @WebParam(name = "transfer", targetNamespace = "http://tempuri.org/")
        MoneyTransfer transfer);

    /**
     * 
     * @param address
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(action = "http://tempuri.org/IBankService/registerClient")
    @WebResult(name = "registerClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "registerClient", targetNamespace = "http://tempuri.org/", className = "pl.bb.broker.company.invoices.rest.bankclient.RegisterClient")
    @ResponseWrapper(localName = "registerClientResponse", targetNamespace = "http://tempuri.org/", className = "pl.bb.broker.company.invoices.rest.bankclient.RegisterClientResponse")
    public Long registerClient(
        @WebParam(name = "address", targetNamespace = "http://tempuri.org/")
        String address);

}
